# Generated by Django 4.0.4 on 2022-10-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='photo/%Y/%m'),
        ),
    ]
