# Generated by Django 4.0.4 on 2022-05-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=64, verbose_name='图片名称')),
                ('photo_time', models.DateField(verbose_name='拍摄时间')),
                ('photo_path', models.FilePathField(verbose_name='存储路径')),
                ('upload_time', models.DateField(verbose_name='上传时间')),
                ('owner', models.CharField(max_length=32, verbose_name='拥有人')),
                ('note', models.TextField(blank=True, null=True, verbose_name='介绍')),
            ],
        ),
    ]
