# Generated by Django 4.0.4 on 2022-05-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools_name', models.CharField(max_length=64, verbose_name='小工具')),
                ('tools_desc', models.CharField(max_length=128, verbose_name='功能表述')),
            ],
        ),
    ]
