# Generated by Django 4.0.4 on 2022-05-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0003_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_path',
            field=models.CharField(max_length=332, verbose_name='存储路径'),
        ),
    ]
