# Generated by Django 4.0.4 on 2022-06-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0005_alter_photo_photo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='tools_desc',
            field=models.TextField(verbose_name='功能表述'),
        ),
    ]
