# Generated by Django 4.0.4 on 2022-06-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0006_alter_tools_tools_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='area',
            field=models.CharField(default='华北', max_length=32, verbose_name='区域'),
        ),
    ]
