# Generated by Django 4.0.4 on 2022-10-08 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0009_alter_data_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
