# Generated by Django 4.0.4 on 2022-10-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools_name', models.CharField(max_length=64, verbose_name='小工具')),
                ('tools_desc', models.TextField(verbose_name='功能表述')),
                ('tools_freq', models.SmallIntegerField(verbose_name='使用频率')),
            ],
        ),
    ]
