# Generated by Django 4.0.4 on 2022-10-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='tools_icon',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
