# Generated by Django 4.0.4 on 2022-12-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_alter_tools_tools_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='tools_icon',
            field=models.ImageField(blank=True, upload_to='static/img/tools_icon'),
        ),
    ]
