# Generated by Django 4.0.4 on 2022-05-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
