# Generated by Django 4.0.4 on 2022-06-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=20, verbose_name='管理员名')),
                ('admin_pwd', models.CharField(max_length=20, verbose_name='管理员密码')),
            ],
        ),
    ]
