# Generated by Django 4.0.4 on 2022-06-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_name',
            field=models.CharField(max_length=60, verbose_name='管理员名'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_pwd',
            field=models.CharField(max_length=60, verbose_name='管理员密码'),
        ),
    ]
