# Generated by Django 4.0.4 on 2022-06-09 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_admin_admin_name_alter_admin_admin_pwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='任务名称')),
                ('content', models.TextField(verbose_name='任务内容')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.SmallIntegerField(choices=[(1, '进行中'), (2, '已完成'), (3, '已取消')], default=1, verbose_name='任务状态')),
                ('level', models.SmallIntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级')], default=1, verbose_name='任务级别')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='任务所属人')),
            ],
        ),
    ]
