# Generated by Django 4.0.4 on 2022-10-13 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqData', '0002_companyinfo_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='area',
        ),
        migrations.RemoveField(
            model_name='data',
            name='company',
        ),
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
