# Generated by Django 4.0.4 on 2022-10-13 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqData', '0003_remove_data_area_remove_data_company_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='endpoint',
            table='seqData',
        ),
    ]
