# Generated by Django 4.0.4 on 2022-10-13 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqData', '0004_alter_endpoint_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EndPoint',
        ),
    ]
