# Generated by Django 4.0.4 on 2022-10-13 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqData', '0006_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='endpoint',
            table=None,
        ),
    ]
