# Generated by Django 4.0.4 on 2022-10-13 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seqData', '0007_alter_endpoint_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(choices=[('华东', 'oss-cn-hangzhou.aliyuncs.com'), ('华北2(北京)', 'oss-cn-beijing.aliyuncs.com'), ('华东2(上海)', 'oss-cn-shanghai.aliyuncs.com')], max_length=7)),
                ('bucket', models.CharField(max_length=300, verbose_name='授权路径')),
                ('KeyID', models.CharField(max_length=100, verbose_name='keyID')),
                ('KeySecret', models.CharField(max_length=100, verbose_name='keySecret')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_path', models.CharField(max_length=332, verbose_name='数据路径')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seqData.endpoint', verbose_name='区域')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seqData.companyinfo', verbose_name='测序公司')),
            ],
        ),
    ]
