# Generated by Django 4.0.4 on 2022-10-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqData', '0008_companyinfo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='endpoint',
            field=models.CharField(choices=[('华东', 'oss-cn-hangzhou.aliyuncs.com'), ('华北2(北京)', 'oss-cn-beijing.aliyuncs.com'), ('华东2(上海)', 'oss-cn-shanghai.aliyuncs.com')], max_length=17),
        ),
    ]
