# Generated by Django 4.0.4 on 2022-10-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqData', '0010_data_ctime'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(default=2, max_length=64, verbose_name='公司名称'),
            preserve_default=False,
        ),
    ]
